### ISSUE TITLE
Visitors with items in their cart can sign up

### ISSUE THREAD

**Issue by calebonesimus** [tiy-indianapolis-ror-june2015/DannyCalebWeek8Lab#23]
All items in the temp cart go to their permanent cart

**Comment by beyrerdn** [comment]
Add a button to the cart page, make sure that once signed up, cart is redefined to their personal cart

**Comment by beyrerdn** [comment]
All items in the temp cart go to a permanent cart assigned to the user, but the user doesn't know about its cart. So, example, cart.user shows a user with user_id of 4, but a User.find(4).cart shows undefined method 'cart' for class User

**Comment by beyrerdn** [comment]
This works.
